import { Template, WorkflowBlock, ApiComponent, DAppProject } from './types';

export const TEMPLATES: Template[] = [
  {
    id: 'token-dashboard',
    name: 'Token Dashboard',
    description: 'Display token balances, transaction history, and transfer forms with real-time updates.',
    suggestedUseCase: 'Fungible token apps, DeFi dashboards, rewards portals',
    includedComponents: ['Balance card', 'Transfer form', 'Transaction history', 'Wallet connect'],
    status: 'Mock template',
    apiIds: ['identity', 'wallet', 'ledger'],
    permissionModel: 'role-based',
  },
  {
    id: 'nft-mint',
    name: 'NFT Mint Page',
    description: 'Mint NFTs with metadata, preview the collection, and track on-chain ownership.',
    suggestedUseCase: 'NFT collections, digital asset issuance, creator platforms',
    includedComponents: ['Mint button', 'Collection preview', 'Metadata form', 'Wallet connect'],
    status: 'Mock template',
    apiIds: ['identity', 'wallet', 'smart-contract'],
    permissionModel: 'wallet-gated',
  },
  {
    id: 'dao-voting',
    name: 'DAO Voting Portal',
    description: 'Create and vote on proposals with on-chain quorum tracking and role-based participation.',
    suggestedUseCase: 'DAOs, governance platforms, community decision tools',
    includedComponents: ['Proposal card', 'Vote buttons', 'Quorum display', 'Results chart'],
    status: 'Mock template',
    apiIds: ['identity', 'permissions', 'bft'],
    permissionModel: 'role-based',
  },
  {
    id: 'escrow-payment',
    name: 'Escrow / Payment App',
    description: 'Multi-party escrow with conditional release, audit trail, and BFT-verified settlement.',
    suggestedUseCase: 'Marketplace payments, freelance contracts, multi-sig workflows',
    includedComponents: ['Sender/receiver fields', 'Payment status', 'Release trigger', 'Audit log'],
    status: 'Mock template',
    apiIds: ['identity', 'wallet', 'ledger', 'bft'],
    permissionModel: 'multi-party',
  },
  {
    id: 'ledger-app',
    name: 'Ledger / Transaction History',
    description: 'Immutable ledger viewer with filtering, export, and BFT-verified entry integrity.',
    suggestedUseCase: 'Aviation records, supply chain, financial audit, compliance logs',
    includedComponents: ['Transaction table', 'Filter panel', 'BFT badge', 'Export button'],
    status: 'Mock template',
    apiIds: ['identity', 'ledger', 'permissions'],
    permissionModel: 'role-based',
  },
  {
    id: 'permissioned-workflow',
    name: 'Permissioned Internal Workflow',
    description: 'Access-controlled workflow with role-gated steps, approval queues, and notifications.',
    suggestedUseCase: 'Internal tools, compliance workflows, enterprise automation',
    includedComponents: ['Workflow steps', 'Approval queue', 'Role gates', 'Notification panel'],
    status: 'Coming soon',
    apiIds: ['identity', 'permissions', 'workflow', 'notifications'],
    permissionModel: 'role-based',
  },
  {
    id: 'custom',
    name: 'Build from Scratch',
    description: 'Start with a blank canvas — pick your own APIs, define your own workflow, and generate a fully custom dApp.',
    suggestedUseCase: "Any dApp that doesn't fit a standard pattern",
    includedComponents: ['Your choice of API components', 'Custom workflow blocks'],
    status: 'Custom',
    apiIds: [],
    permissionModel: 'role-based',
  },
];

export const API_COMPONENTS: ApiComponent[] = [
  {
    id: 'identity',
    name: 'User Identity API',
    purpose: 'Verify user identity, manage sessions, and retrieve profile data including dApp access list.',
    endpoint: '/api/identity/me',
    inputOutput: 'Input: auth token → Output: user profile, roles, dApp access list',
    securityNote: 'Requires authenticated user',
    securityLevel: 'auth',
  },
  {
    id: 'wallet',
    name: 'Wallet Session API',
    purpose: 'Initiate wallet connection, sign messages, and manage wallet session tokens.',
    endpoint: '/api/wallet/connect',
    inputOutput: 'Input: wallet address → Output: session token, signed challenge',
    securityNote: 'Requires authenticated user',
    securityLevel: 'auth',
  },
  {
    id: 'ledger',
    name: 'Ledger API',
    purpose: 'Read and write immutable ledger entries with BFT-verified integrity proofs.',
    endpoint: '/api/ledger/entries',
    inputOutput: 'Input: dApp ID, filters → Output: entries[], BFT proof hash',
    securityNote: 'Requires dApp permission',
    securityLevel: 'dapp',
  },
  {
    id: 'bft',
    name: 'BFT Transaction API',
    purpose: 'Submit transactions for Byzantine Fault Tolerant consensus and quorum verification.',
    endpoint: '/api/bft/submit',
    inputOutput: 'Input: tx payload → Output: quorum result, consensus hash',
    securityNote: 'Admin only',
    securityLevel: 'admin',
  },
  {
    id: 'permissions',
    name: 'Permissioning API',
    purpose: 'Check and enforce dApp-level access control rules per user, resource, and action.',
    endpoint: '/api/permissions/check-access',
    inputOutput: 'Input: user ID, resource, action → Output: allowed: boolean, reason',
    securityNote: 'Requires dApp permission',
    securityLevel: 'dapp',
  },
  {
    id: 'notifications',
    name: 'Notification API',
    purpose: 'Send in-app and webhook notifications to users and external services.',
    endpoint: '/api/notifications/send',
    inputOutput: 'Input: recipient, message, channel → Output: delivery status',
    securityNote: 'Requires dApp permission',
    securityLevel: 'dapp',
  },
  {
    id: 'workflow',
    name: 'Workflow Orchestration API',
    purpose: 'Execute multi-step workflows with state tracking, retry logic, and step callbacks.',
    endpoint: '/api/workflows/run',
    inputOutput: 'Input: workflow config, context → Output: step results[], final state',
    securityNote: 'Requires dApp permission',
    securityLevel: 'dapp',
  },
  {
    id: 'smart-contract',
    name: 'Smart Contract Adapter API',
    purpose: 'Invoke smart contract methods and read on-chain state via a secure adapter layer.',
    endpoint: '/api/contracts/invoke',
    inputOutput: 'Input: contract address, method, params → Output: tx hash, result',
    securityNote: 'Admin only',
    securityLevel: 'admin',
  },
];

export const WORKFLOW_BLOCKS: WorkflowBlock[] = [
  { id: 'authenticate-user', label: 'Authenticate user', apiId: 'identity' },
  { id: 'check-dapp-permission', label: 'Check dApp permission', apiId: 'permissions' },
  { id: 'connect-wallet', label: 'Connect wallet placeholder', apiId: 'wallet' },
  { id: 'read-ledger-entries', label: 'Read ledger entries', apiId: 'ledger' },
  { id: 'submit-transaction', label: 'Submit transaction', apiId: 'ledger' },
  { id: 'trigger-bft-quorum', label: 'Trigger BFT quorum', apiId: 'bft' },
  { id: 'generate-notification', label: 'Generate notification', apiId: 'notifications' },
  { id: 'save-result', label: 'Save result', apiId: 'workflow' },
];

export const TEMPLATE_DEFAULT_BLOCKS: Record<string, string[]> = {
  'token-dashboard': ['authenticate-user', 'connect-wallet', 'read-ledger-entries'],
  'nft-mint': ['authenticate-user', 'connect-wallet', 'submit-transaction'],
  'dao-voting': ['authenticate-user', 'check-dapp-permission', 'trigger-bft-quorum'],
  'escrow-payment': ['authenticate-user', 'connect-wallet', 'submit-transaction', 'trigger-bft-quorum'],
  'ledger-app': ['authenticate-user', 'check-dapp-permission', 'read-ledger-entries'],
  'permissioned-workflow': ['authenticate-user', 'check-dapp-permission', 'generate-notification', 'save-result'],
  'custom': [],
};

export const DEMO_PROJECTS: DAppProject[] = [
  { id: 'aviation-ledger', name: 'Aviation Ledger App', status: 'Draft', templateId: 'ledger-app' },
  { id: 'token-rewards', name: 'Token Rewards Portal', status: 'Preview', templateId: 'token-dashboard' },
  { id: 'dao-voting-demo', name: 'DAO Voting Demo', status: 'Ready for API mapping', templateId: 'dao-voting' },
  { id: 'escrow-flow', name: 'Escrow Payment Flow', status: 'Permission review', templateId: 'escrow-payment' },
];
