import React from 'react';
import { Sparkles } from 'lucide-react';
import { Template, WorkflowBlock } from '../types';

interface Props {
  selectedTemplate: Template | null;
  workflowSteps: WorkflowBlock[];
}

const TS_STUB = `// Auto-generated by DApp Builder — do not edit manually
import { IdentityClient, LedgerClient, PermissionsClient } from '@goknown/dapp-sdk';

interface LedgerEntry {
  id:        string;
  timestamp: string;
  action:    string;
  actor:     string;
  hash:      string;
}

/**
 * Fetch ledger entries for the authenticated user's dApp context.
 * Generated from template: ledger-app
 * Workflow: authenticate → check-permission → read-ledger
 */
export async function fetchLedgerEntries(
  authToken: string,
  dappId:    string
): Promise<LedgerEntry[]> {
  const identity = new IdentityClient({ token: authToken });
  const user     = await identity.getProfile();          // authenticate-user

  const perms    = new PermissionsClient({ userId: user.id });
  const allowed  = await perms.checkAccess(dappId, 'ledger', 'read');
  if (!allowed) throw new Error('Permission denied');    // check-dapp-permission

  const ledger   = new LedgerClient({ dappId });
  return ledger.getEntries({ limit: 50 });               // read-ledger-entries
}`;

const API_STUB = `// API route — /api/dapps/:dappId/ledger (Express-style pseudocode)

router.get('/api/dapps/:dappId/ledger', requireAuth(), async (req, res) => {
  const { dappId } = req.params;
  const { userId } = req.user;                    // injected by requireAuth middleware

  // 1. Check dApp-level permission
  const allowed = await permissionsService.checkAccess({
    userId, resource: dappId, action: 'ledger:read',
  });
  if (!allowed) return res.status(403).json({ error: 'Forbidden' });

  // 2. Fetch entries from Ledger API
  const entries = await ledgerService.getEntries({ dappId, limit: 50 });

  // 3. Attach BFT proof
  const proof = await bftService.getProof(entries.latestHash);

  return res.json({ entries: entries.data, proof, total: entries.count });
});`;

const WORKFLOW_STUB = `// Workflow execution pseudocode — generated from dapp.config.json
// Orchestrated by WorkflowOrchestration API at /api/workflows/run

async function runAviationLedgerWorkflow(context: WorkflowContext) {
  const result: Record<string, unknown> = {};

  // Step 1 — authenticate-user
  result.user = await step('authenticate-user', () =>
    identityApi.verifyToken(context.authToken)
  );

  // Step 2 — check-dapp-permission
  result.access = await step('check-dapp-permission', () =>
    permissionsApi.checkAccess({
      userId:   result.user.id,
      resource: context.dappId,
      action:   'read',
    })
  );
  if (!result.access.allowed) throw new WorkflowError('Permission denied', 'step-2');

  // Step 3 — read-ledger-entries
  result.ledger = await step('read-ledger-entries', () =>
    ledgerApi.getEntries({ dappId: context.dappId, filters: context.filters })
  );

  return { status: 'complete', steps: 3, payload: result };
}`;

interface CodeBlockProps {
  label: string;
  lang: string;
  code: string;
}

function CodeBlock({ label, lang, code }: CodeBlockProps) {
  return (
    <div className="code-block">
      <div className="code-block-header">
        <span className="code-block-label">{label}</span>
        <span className="code-block-lang">{lang}</span>
      </div>
      <pre className="code-block-body">{code}</pre>
    </div>
  );
}

export function CodeGenerationPreview({ selectedTemplate, workflowSteps }: Props) {
  const hasContext = selectedTemplate || workflowSteps.length > 0;

  return (
    <div className="pane">
      <div className="pane-header">
        <p className="pane-kicker">AI-Assisted Code Generation</p>
        <h2 className="pane-title">Generated code preview</h2>
        <p className="pane-desc">
          Future versions of DApp Builder will generate production-ready code directly from your
          workflow config via a secure server-side API. No API keys are exposed to the frontend;
          all generation happens within the platform's trusted compute boundary.
        </p>
      </div>

      <div className="code-gen-intro">
        <h3>
          <Sparkles size={16} style={{ verticalAlign: 'middle', marginRight: '8px', color: '#4ee5ff' }} />
          How AI code generation will work
        </h3>
        <p>
          Your <code style={{ color: '#4ee5ff', background: 'rgba(78,229,255,0.08)', padding: '1px 6px', borderRadius: '5px', fontFamily: 'monospace' }}>dapp.config.json</code> is
          sent to a server-side generation endpoint. The platform's AI models produce TypeScript
          SDK calls, Express-style API routes, and orchestration stubs — all reviewed before
          deployment. The preview below shows static example output for the Aviation Ledger
          workflow{hasContext && selectedTemplate ? ` (template: ${selectedTemplate.name})` : ''}.
        </p>
      </div>

      <div className="code-blocks-grid">
        <CodeBlock
          label="TypeScript SDK stub"
          lang="TypeScript"
          code={TS_STUB}
        />
        <CodeBlock
          label="API route pseudocode"
          lang="Pseudocode / Express"
          code={API_STUB}
        />
        <CodeBlock
          label="Workflow execution pseudocode"
          lang="Pseudocode"
          code={WORKFLOW_STUB}
        />
      </div>
    </div>
  );
}
